### ISSUE TITLE
invalid $studiendekan at Vorwort

### ISSUE THREAD

**Issue by tobkratz** [d120/cyberinforz#1]
## Issue
Nach intensiever recherche auf teils ominösen Seiten[1] hat sich gezeigt, dass anders als ins src/wilkommen/vorwort.md Prof. Dr. Marc Fischlin (Studiendekan) kein Studiendekan ist. 

```
![Prof. Dr. Marc Fischlin][dekan]
<center><strong>Prof. Dr. Marc Fischlin</center></strong>

[dekan]: ../_res/img/fischlin_studiendekan.jpg "Prof. Dr. Marc Fischlin"
```
(src/wilkommen/vortwort.md):

Außerdem ist in der Beschreibung der Bilder Fischlin als dekan beschrieben, müsste allerdings studiendekan heißen.

## Steps to reproduce
- `mdbook serve`
- navigate to `http://localhost:3000/willkommen/vorwort.html`

[1] = https://www.informatik.tu-darmstadt.de/fb20/organisation_fb20/dekanat/index.de.jsp

**Comment by Xiphoseer** [comment]
Ein Vorwort ist angefragt, wir werden das CyberInforz aber diese OPhase nicht verwenden.
